---
# tasks file for docker

- name: Apt-get install requirements
  apt: name={{item}} state=installed
  with_items:
       - apt-transport-https
       - ca-certificates
       - curl
       - python-software-properties


- name: "Install docker apt key"
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D state=present

- apt_repository:
    repo: deb https://apt.dockerproject.org/repo ubuntu-yakkety main
    state: present

- name: Install docker
  apt:
   name: docker-engine
   state: present
   update_cache: yes

- name: Update permissions
  shell: "gpasswd -a vagrant docker"

- name: Spawn group
  shell: "newgrp docker"

- copy:
    src:  ../resources/docker-tcp.socket
    dest: /etc/systemd/system/docker-tcp.socket
    owner: root
    group: root
    mode: 0644

- systemd:
    name: docker-tcp.socket
    enabled: yes

- systemd:
    name: docker.socket
    enabled: yes

- systemd:
    name: docker
    state: stopped

- systemd:
    name: docker-tcp.socket
    state: started

- systemd:
    name: docker
    state: started

- name: Install docker machine
  shell: "curl -L https://github.com/docker/machine/releases/download/v0.9.0/docker-machine-`uname -s`-`uname -m` >/tmp/docker-machine &&
  chmod +x /tmp/docker-machine &&
  sudo cp /tmp/docker-machine /usr/local/bin/docker-machine"
